// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpqyr9e7ndP96oyYWlqGqxC9xf-GHdS4s',
    appId: '1:851914512004:web:a26555bfa405038aaf14d1',
    messagingSenderId: '851914512004',
    projectId: 'chat-test-9ac2e',
    authDomain: 'chat-test-9ac2e.firebaseapp.com',
    storageBucket: 'chat-test-9ac2e.appspot.com',
    measurementId: 'G-QBZXCYF7MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBWxoLldqYFHZ-xa6j03D10DV8ZrwY4L4',
    appId: '1:851914512004:android:a2b9f4d144274df0af14d1',
    messagingSenderId: '851914512004',
    projectId: 'chat-test-9ac2e',
    storageBucket: 'chat-test-9ac2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgiIlW_KIJo7YUoMowV2RzOhit2uGkf8Y',
    appId: '1:851914512004:ios:4cad9613cd1ae10faf14d1',
    messagingSenderId: '851914512004',
    projectId: 'chat-test-9ac2e',
    storageBucket: 'chat-test-9ac2e.appspot.com',
    iosBundleId: 'com.example.chatTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgiIlW_KIJo7YUoMowV2RzOhit2uGkf8Y',
    appId: '1:851914512004:ios:6da1eeeda8eafcdaaf14d1',
    messagingSenderId: '851914512004',
    projectId: 'chat-test-9ac2e',
    storageBucket: 'chat-test-9ac2e.appspot.com',
    iosBundleId: 'com.example.chatTest.RunnerTests',
  );
}
